import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { getCwd } from '../utils/paths.mjs';
import { refreshContext } from '../core/context.mjs';
import { extractFacts, generateSyncPlan, readLightweightFacts } from '../core/sync-plan.mjs';
import { readRules } from '../core/rules.mjs';
import { parseProtectedSections, checkProtectedContent } from '../core/protected-content.mjs';
import { writeText } from '../utils/fs.mjs';

const CORE_DOCS = ['README.md', 'AGENTS.md', 'CLAUDE.md'];

/**
 * Run markdownlint fix on target files.
 */
export async function runMarkdownFix(cwd, files = []) {
  try {
    const args = files.length > 0
      ? ['npx', '--yes', 'markdownlint-cli2', '--fix', ...files]
      : ['npx', '--yes', 'markdownlint-cli2', '--fix', '**/*.md', '#node_modules'];
    execSync(args.join(' '), { cwd, stdio: 'pipe', timeout: 15000 });
    return { ok: true, verification: 'markdownlint completed' };
  } catch (err) {
    return { ok: false, verification: `markdownlint failed: ${err.message}` };
  }
}

/**
 * Check if fast sync has enough information to proceed.
 */
function hasEnoughGitFacts(lightweightFacts) {
  if (!lightweightFacts.gitAvailable) return false;
  if (lightweightFacts.lastCommit) return true;
  if (lightweightFacts.diffNames) return true;
  if (lightweightFacts.statusShort) return true;
  return false;
}

/**
 * Check if fast sync involves high-risk content that requires full sync.
 */
function isHighRiskContent(lightweightFacts, rules) {
  const riskKeywords = [
    '安装方式', 'command', '契约', '测试命令', '安全约束',
    'directory', '结构', 'install', 'deploy', 'test', 'security',
    'constraint', 'setup', 'architecture', 'api', 'endpoint',
  ];

  const content = [
    lightweightFacts.lastCommit || '',
    lightweightFacts.diffNames || '',
    lightweightFacts.statusShort || '',
  ].join(' ').toLowerCase();

  for (const kw of riskKeywords) {
    if (content.includes(kw.toLowerCase())) return true;
  }

  // Check if any target doc would need structural changes
  if (rules?.override?.includes('protected') || rules?.override?.includes('保护')) {
    return true;
  }

  return false;
}

/**
 * Infer which docs need updating from git diff.
 */
function inferImpactFromDiff(lightweightFacts) {
  if (!lightweightFacts.diffNames) return CORE_DOCS;

  const changedFiles = lightweightFacts.diffNames.split('\n').filter(Boolean);
  const impacted = new Set();

  for (const file of changedFiles) {
    const lower = file.toLowerCase();
    // Source code changes → all docs might need update
    if (lower.startsWith('src/') || lower.startsWith('bin/')) {
      return CORE_DOCS;
    }
    // Template changes → docs might need update
    if (lower.startsWith('templates/')) {
      return CORE_DOCS;
    }
    // Specific doc changes → only that doc
    if (lower === 'readme.md') impacted.add('README.md');
    else if (lower === 'agents.md') impacted.add('AGENTS.md');
    else if (lower === 'claude.md') impacted.add('CLAUDE.md');
  }

  return impacted.size > 0 ? [...impacted] : CORE_DOCS;
}

/**
 * Apply edit plan using AI-provided instructions.
 * This function computes the actual edit based on facts and rules,
 * then returns the proposed changes for the AI to review and apply.
 */
export function computeEdits(facts, rules, targetDoc, instruction = '') {
  const current = facts[targetDoc === 'README.md' ? 'readme' : targetDoc === 'AGENTS.md' ? 'agents' : 'claude'];

  if (!current) {
    // Document doesn't exist — provide a template
    const templates = {
      'README.md': '# Project\n\n## Overview\n\nTODO: Add project description\n\n## Installation\n\nTODO: Add installation instructions\n\n## Usage\n\nTODO: Add usage instructions\n',
      'AGENTS.md': '# AGENTS.md\n\n## Project Overview\n\nTODO: Add project overview\n\n## DocSync\n\nSee .docsync/ for document sync configuration.\n',
      'CLAUDE.md': '# CLAUDE.md\n\n## Project Context\n\nTODO: Add project context\n',
    };
    return { action: 'create', content: templates[targetDoc] || `# ${targetDoc}\n\n` };
  }

  // With an AI instruction, the edit would be generated by the AI.
  // Here we return the current content with metadata for the AI to review.
  return { action: 'review', content: current, factsUsed: [] };
}

/**
 * Update last-sync.json with current state.
 */
export async function updateLastSync(cwd, report) {
  const stateDir = join(cwd, '.docsync', 'state');
  const lastSyncPath = join(stateDir, 'last-sync.json');

  const state = {
    lastSyncAt: new Date().toISOString(),
    mode: report.mode,
    updatedFiles: report.updated,
    skippedFiles: report.skipped,
    factsUsed: report.factsUsed,
  };

  await writeText(lastSyncPath, JSON.stringify(state, null, 2));
}

/**
 * Execute full document sync.
 */
export async function syncFull(cwd, targets = []) {
  const contextDir = join(cwd, '.docsync', 'context');

  // 1. Refresh context
  const ctxResults = await refreshContext(cwd);

  // 2. Extract facts
  const facts = await extractFacts(cwd);

  // 3. Read rules
  const rules = readRules(cwd);

  // 4. Parse protected content
  const protectedSections = parseProtectedSections(rules.override || '');

  // 5. Generate sync plan
  const docTargets = targets.length > 0 ? targets : CORE_DOCS;
  const plan = await generateSyncPlan(docTargets, facts, rules, 'full', cwd);

  // 6. Compute actual edits for each target
  const edits = [];
  for (const targetDoc of plan.updated) {
    const edit = computeEdits(facts, rules, targetDoc);
    if (edit.action === 'create' || edit.action === 'update') {
      // Check protected content before adding to edits
      try {
        checkProtectedContent([{ file: targetDoc, content: edit.content }], protectedSections);
        edits.push({ file: targetDoc, newContent: edit.content });
      } catch (err) {
        plan.skipped.push({ file: targetDoc, reason: `protected content conflict: ${err.message}` });
        plan.updated = plan.updated.filter(f => f !== targetDoc);
        plan.todoReview.push(`Protected content conflict in ${targetDoc}`);
      }
    }
  }

  // 7. Apply edits via transaction
  if (edits.length > 0) {
    const { transaction } = await import('../core/transaction.mjs');
    // Use relative paths (transaction expects file names, not absolute paths)
    const resolvedEdits = edits.map(e => ({
      file: e.file,
      newContent: e.newContent,
      basePath: cwd,
    }));

    try {
      await transaction(resolvedEdits, (editsToValidate) => {
        checkProtectedContent(editsToValidate, protectedSections);
      });
    } catch (err) {
      plan.todoReview.push(`Transaction failed: ${err.message}`);
      return { ...plan, verification: 'transaction failed' };
    }
  }

  // 8. Run markdown fix on updated files
  const fixedFiles = plan.updated.map(f => join(cwd, f));
  const fixResult = await runMarkdownFix(cwd, fixedFiles);

  // 9. Build report
  const report = {
    updated: plan.updated,
    skipped: plan.skipped,
    factsUsed: plan.factsUsed,
    mode: 'full',
    todoReview: plan.todoReview,
    verification: fixResult.verification,
  };

  // 10. Update last-sync.json
  await updateLastSync(cwd, report);

  return report;
}

/**
 * Execute fast document sync.
 * Upgrades to full sync if git facts are insufficient or high-risk.
 */
export async function syncFast(cwd, targets = []) {
  // 1. Read lightweight facts
  const lightweightFacts = await readLightweightFacts(cwd);

  // 2. Read last-sync state
  const lastSyncPath = join(cwd, '.docsync', 'state', 'last-sync.json');
  let lastSync = null;
  if (existsSync(lastSyncPath)) {
    lastSync = JSON.parse(readFileSync(lastSyncPath, 'utf8'));
  }

  // 3. Check if we have enough git facts
  if (!hasEnoughGitFacts(lightweightFacts)) {
    return {
      updated: [],
      skipped: [],
      factsUsed: [],
      mode: 'fast-upgraded-to-full',
      todoReview: ['Insufficient git facts, upgraded to full sync'],
      verification: 'none',
      upgraded: true,
    };
  }

  // 4. Check for high-risk content
  const rules = readRules(cwd);
  if (isHighRiskContent(lightweightFacts, rules)) {
    return {
      updated: [],
      skipped: [],
      factsUsed: [],
      mode: 'fast-upgraded-to-full',
      todoReview: ['High-risk content detected, upgraded to full sync'],
      verification: 'none',
      upgraded: true,
    };
  }

  // 5. Infer impact from diff
  const docTargets = targets.length > 0 ? targets : inferImpactFromDiff(lightweightFacts);

  // 6. Extract facts for report
  const facts = await extractFacts(cwd);

  // 7. Generate plan
  const plan = await generateSyncPlan(docTargets, facts, rules, 'fast', cwd);

  // 8. Parse protected content
  const protectedSections = parseProtectedSections(rules.override || '');

  // 9. Compute edits (fast mode — minimal changes)
  const edits = [];
  for (const targetDoc of plan.updated) {
    const edit = computeEdits(facts, rules, targetDoc);
    if (edit.action === 'create' || edit.action === 'update') {
      try {
        checkProtectedContent([{ file: targetDoc, content: edit.content }], protectedSections);
        edits.push({ file: targetDoc, newContent: edit.content });
      } catch (err) {
        plan.skipped.push({ file: targetDoc, reason: `protected content conflict: ${err.message}` });
        plan.updated = plan.updated.filter(f => f !== targetDoc);
      }
    }
  }

  // 10. Apply edits
  if (edits.length > 0) {
    const { transaction } = await import('../core/transaction.mjs');
    // Use relative paths (transaction expects file names, not absolute paths)
    const resolvedEdits = edits.map(e => ({
      file: e.file,
      newContent: e.newContent,
      basePath: cwd,
    }));

    try {
      await transaction(resolvedEdits, (editsToValidate) => {
        checkProtectedContent(editsToValidate, protectedSections);
      });
    } catch (err) {
      plan.todoReview.push(`Transaction failed: ${err.message}`);
    }
  }

  // 11. Run markdown fix
  const fixedFiles = plan.updated.map(f => join(cwd, f));
  const fixResult = await runMarkdownFix(cwd, fixedFiles);

  // 12. Build report
  const report = {
    updated: plan.updated,
    skipped: plan.skipped,
    factsUsed: plan.factsUsed,
    mode: 'fast',
    todoReview: plan.todoReview,
    verification: fixResult.verification,
  };

  await updateLastSync(cwd, report);

  return report;
}

/**
 * CLI entry point for sync command.
 * Called from cli.mjs with parsed options.
 */
export async function runSync(options = {}) {
  const cwd = getCwd(options);
  const { fast = false, targets = [], quiet = false } = options;

  // Verify .docsync/ workspace exists
  const installPath = join(cwd, '.docsync', 'state', 'install.json');
  if (!existsSync(installPath)) {
    process.stderr.write('Error: DocSync not initialized. Run npx first, then /docsync:init\n');
    process.exitCode = 1;
    return;
  }

  // Validate workspace
  const requiredDirs = ['config', 'context', 'rules'];
  for (const dir of requiredDirs) {
    if (!existsSync(join(cwd, '.docsync', dir))) {
      process.stderr.write(`Error: .docsync/${dir}/ is missing. Re-run npx bootstrap.\n`);
      process.exitCode = 1;
      return;
    }
  }

  const docTargets = targets.length > 0 ? targets : CORE_DOCS;

  if (!quiet) {
    process.stdout.write(`\nDocSync ${fast ? 'Fast' : 'Full'} Sync\n`);
    process.stdout.write(`Targets: ${docTargets.join(', ')}\n`);
  }

  const report = fast
    ? await syncFast(cwd, docTargets)
    : await syncFull(cwd, docTargets);

  // Handle upgrade from fast to full
  if (report.upgraded) {
    if (!quiet) {
      process.stdout.write(`\nFast sync cannot proceed safely. Upgrading to full sync...\n`);
    }
    const fullReport = await syncFull(cwd, docTargets);
    if (!quiet) {
      printReport(fullReport);
    }
    return fullReport;
  }

  if (!quiet) {
    printReport(report);
  }

  return report;
}

/**
 * Print sync report to stdout.
 */
function printReport(report) {
  process.stdout.write('\n=== Sync Report ===\n');
  process.stdout.write(`Mode: ${report.mode}\n`);

  if (report.updated.length > 0) {
    process.stdout.write(`\nUpdated (${report.updated.length}):\n`);
    for (const f of report.updated) {
      process.stdout.write(`  ✓ ${f}\n`);
    }
  }

  if (Array.isArray(report.skipped) && report.skipped.length > 0) {
    process.stdout.write(`\nSkipped (${report.skipped.length}):\n`);
    for (const item of report.skipped) {
      const reason = typeof item === 'string' ? item : `${item.file}: ${item.reason}`;
      process.stdout.write(`  - ${reason}\n`);
    }
  }

  if (report.factsUsed.length > 0) {
    process.stdout.write(`\nFacts used: ${report.factsUsed.join(', ')}\n`);
  }

  if (report.todoReview && report.todoReview.length > 0) {
    process.stdout.write(`\nTODO Review:\n`);
    for (const item of report.todoReview) {
      process.stdout.write(`  ⚠ ${item}\n`);
    }
  }

  process.stdout.write(`\nVerification: ${report.verification}\n`);
  process.stdout.write('=== End Report ===\n\n');
}
